name: Build Pipeline

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: docker-build-cache
          key: ${{ runner.os }}-docker-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Inject docker-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: docker-build-cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images with docker buildx
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: docker buildx bake --file docker-bake.hcl --push
